// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "fl_munt_ui.h"

void FLMuntUI::cb_button_i(Fl_Button*, void*) {
  printf("Pushed the button!\n");
}
void FLMuntUI::cb_button(Fl_Button* o, void* v) {
  ((FLMuntUI*)(o->parent()->user_data()))->cb_button_i(o,v);
}

Fl_Double_Window* FLMuntUI::make_window() {
  { w = new Fl_Double_Window(430, 115);
    w->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(335, 15, 80, 25, "button");
      o->callback((Fl_Callback*)cb_button);
    } // Fl_Button* o
    { new Fl_Box(45, 47, 254, 38, "Display");
    } // Fl_Box* o
    { new Fl_Box(100, 14, 140, 21, "MT32EMU");
    } // Fl_Box* o
    { new Fl_Button(335, 45, 80, 25, "button");
    } // Fl_Button* o
    w->end();
  } // Fl_Double_Window* w
  return w;
}

FLMuntUI::FLMuntUI(MuntUIController *controller) {
  make_window();
  w->show();
  c = controller;
}

FLMuntUI::~FLMuntUI() {
  delete w;
}

FLMuntUI::FLMuntUI(MuntUIController *controller, void* parentWindow) {
  make_window();
  fl_open_display();
  fl_embed(w, (Window)parentWindow);
  c = controller;
}
