// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "fl_munt_ui.h"

void FLMuntUI::cb_Debug_i(Fl_Button*, void*) {
  c->test1();
}
void FLMuntUI::cb_Debug(Fl_Button* o, void* v) {
  ((FLMuntUI*)(o->parent()->user_data()))->cb_Debug_i(o,v);
}

void FLMuntUI::cb_Load_i(Fl_Button*, void*) {
  c->test2();
}
void FLMuntUI::cb_Load(Fl_Button* o, void* v) {
  ((FLMuntUI*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

Fl_Double_Window* FLMuntUI::make_window() {
  { w = new Fl_Double_Window(430, 85);
    w->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(335, 15, 80, 25, "Debug");
      o->callback((Fl_Callback*)cb_Debug);
    } // Fl_Button* o
    { display = new LCDDisplay(45, 47, 246, 24, "Display");
      display->box(FL_NO_BOX);
      display->color(FL_BACKGROUND_COLOR);
      display->selection_color(FL_BACKGROUND_COLOR);
      display->labeltype(FL_NORMAL_LABEL);
      display->labelfont(0);
      display->labelsize(14);
      display->labelcolor(FL_FOREGROUND_COLOR);
      display->align(Fl_Align(FL_ALIGN_CENTER));
      display->when(FL_WHEN_RELEASE);
    } // LCDDisplay* display
    { new Fl_Box(100, 14, 140, 21, "MT32EMU");
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(335, 45, 80, 25, "Load syx");
      o->callback((Fl_Callback*)cb_Load);
    } // Fl_Button* o
    w->end();
  } // Fl_Double_Window* w
  return w;
}

FLMuntUI::FLMuntUI(MuntUIController *controller) {
  make_window();
  w->show();
  c = controller;
}

FLMuntUI::~FLMuntUI() {
  delete w;
}

FLMuntUI::FLMuntUI(MuntUIController *controller, void* parentWindow) {
  make_window();
  fl_open_display();
  fl_embed(w, (Window)parentWindow);
  c = controller;
}
