// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef fl_munt_ui_h
#define fl_munt_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/x.H>
#include "munt_ui_controller.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class FLMuntUI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *w;
private:
  void cb_button_i(Fl_Button*, void*);
  static void cb_button(Fl_Button*, void*);
public:
  FLMuntUI(MuntUIController *controller);
  ~FLMuntUI();
  FLMuntUI(MuntUIController *controller, void* parentWindow);
private:
  MuntUIController *c; 
};
#endif
